module.exports = [
    {
      id: 'no-console-log',
      concern: 'behavior',
      category: 'debugging',
      severity: 'warning',
      penalty: 5,
      description: 'Console output should not be committed because it can expose implementation details to end users.',
      suggestion: 'Remove the console call or use an approved logger when diagnostics are intentionally required.',
      pattern: /\bconsole\.(log|debug|info|warn|error)\s*\(/,
    },
    {
      id: 'avoid-use-effect',
      concern: 'behavior',
      category: 'react',
      severity: 'warning',
      penalty: 10,
      description: 'useEffect should only be used when there is no cleaner event-driven or derived-state alternative.',
      suggestion: 'Prefer derived values, event handlers, form APIs, or explicit state flow before using useEffect.',
      pattern: /\buseEffect\s*\(/,
    },
    {
      id: 'too-many-todos',
      concern: 'behavior',
      category: 'maintainability',
      severity: 'warning',
      penalty: 10,
      description: 'Files should not accumulate TODO/FIXME-style comments because they become permanent ambiguity.',
      suggestion: 'Resolve the comments, create tickets, or keep unresolved follow-up comments below the configured threshold.',
      pattern: /\b(?:todo|to\s*do|fixme|fix\s*me|hack|temporary|temp|workaround)\b/i,
      maxOccurrencesPerFile: 3,
    },
    {
      id: 'no-arbitrary-timeout',
      concern: 'behavior',
      category: 'stability',
      severity: 'error',
      penalty: 20,
      description: 'Timers should not be used to hide race conditions, rendering problems, or unresolved async behavior.',
      suggestion: 'Use real state transitions, promises, async queries, mocked timers, or explicit event completion.',
      pattern: /\b(setTimeout|setInterval)\s*\(/,
      allowedPatterns: [/timeout:\s*\d+/, /\btestTimeout\b/, /\bvi\.setConfig\s*\(/, /\bjest\.setTimeout\s*\(/],
    },
    {
      id: 'no-screen-debug',
      concern: 'behavior',
      category: 'testing',
      severity: 'error',
      penalty: 15,
      description: 'screen.debug should be removed before committing because it produces noise and does not prove behavior.',
      suggestion: 'Replace screen.debug with meaningful assertions against visible behavior, role, name, value, or state.',
      pattern: /\bscreen\.debug\s*\(/,
    },
    {
      id: 'no-focused-tests',
      concern: 'behavior',
      category: 'testing',
      severity: 'error',
      penalty: 25,
      description: 'Focused tests can accidentally prevent the full test suite from running.',
      suggestion: 'Remove .only from describe, it, or test.',
      pattern: /\b(describe|it|test)\.only\s*\(/,
    },
    {
      id: 'no-skipped-tests',
      concern: 'behavior',
      category: 'testing',
      severity: 'fatal',
      penalty: 100,
      description: 'Skipped tests hide broken or unfinished behavior.',
      suggestion: 'Fix, remove, or complete the test rather than committing it in a skipped state.',
      analyzer: 'skipped-tests',
    },
    {
      id: 'avoid-array-length-assertions',
      concern: 'behavior',
      category: 'testing',
      severity: 'warning',
      penalty: 10,
      description: 'Array length assertions are often a weak substitute for proving meaningful behavior.',
      suggestion: 'Assert the specific rendered item, role, label, value, call, or behavior that matters.',
      pattern: /expect\s*\([^)]*(?:\.length|getAllBy|queryAllBy|findAllBy)[^)]*\)\s*\.\s*(?:toBe|toEqual|toHaveLength|toBeGreaterThan|toBeLessThan)/,
    },
    {
      id: 'complex-inline-boolean-expression',
      concern: 'behavior',
      category: 'readability',
      severity: 'warning',
      penalty: 8,
      description: 'Complex inline boolean expressions are harder to read and should usually be named.',
      suggestion: 'Extract the expression into a named boolean that explains the business meaning.',
      pattern: /{[^}\n]*(?:&&|\|\|)[^}\n]*(?:&&|\|\||\?)[^}\n]*}/,
    },
    {
      id: 'mixed-logical-operators-in-if',
      concern: 'behavior',
      category: 'readability',
      severity: 'warning',
      penalty: 10,
      description: 'If conditions that mix && and || are easier to misread because operator precedence affects the result.',
      suggestion: 'Extract the condition into named booleans or split the decision flow.',
      pattern: /\bif\s*\([^\n]*(?:(?:&&[^\n]*\|\|)|(?:\|\|[^\n]*&&))[^\n]*\)/,
    },
    {
      id: 'too-many-logical-operators-in-if',
      concern: 'behavior',
      category: 'readability',
      severity: 'warning',
      penalty: 8,
      description: 'Long if conditions are harder to understand when several checks are packed into one expression.',
      suggestion: 'Extract meaningful parts of the condition into named booleans before the if statement.',
      pattern: /\bif\s*\([^\n]*(?:&&|\|\|)[^\n]*(?:&&|\|\|)[^\n]*(?:&&|\|\|)[^\n]*(?:&&|\|\|)[^\n]*\)/,
    },
    {
      id: 'mixed-if-else-and-switch',
      concern: 'behavior',
      category: 'readability',
      severity: 'warning',
      penalty: 10,
      description: 'Mixing if/else-if chains with switch/case logic in the same file can make decision flow harder to follow.',
      suggestion: 'Prefer one clear decision-flow style for a cohesive block of business logic.',
      filePattern: /\b(?:else\s+if|if)\b[\s\S]*?\bswitch\s*\(|\bswitch\s*\([\s\S]*?\belse\s+if\b/,
    },
  ];
  