module.exports = [
    {
      id: 'inline-nullish-fallback',
      concern: 'testability',
      category: 'branch-noise',
      key: '??',
      severity: 'warning',
      penalty: 8,
      pattern: /\?\?/,
      description: 'Nullish fallback can create a branch that obscures meaningful coverage gaps.',
      suggestion: 'Test both outcomes when behavior matters, or extract the fallback into a named boundary/helper.',
      coverageCandidate: true,
    },
    {
      id: 'inline-logical-fallback',
      concern: 'testability',
      category: 'branch-noise',
      key: '||',
      severity: 'warning',
      penalty: 8,
      pattern: /(?:const|let|var|return)\s+.*\|\|/,
      description: 'Logical fallback can create branch noise or hide an implicit default.',
      suggestion: 'Prefer an explicit default when it communicates intent more clearly.',
      coverageCandidate: true,
    },
    {
      id: 'optional-callback',
      concern: 'testability',
      category: 'branch-noise',
      key: '?.()',
      severity: 'warning',
      penalty: 10,
      pattern: /\?\.\s*\(/,
      description: 'Optional callback invocation creates a branch that may be difficult to exercise meaningfully.',
      suggestion: 'Test both callback-present and callback-absent behavior when meaningful, or make the boundary explicit.',
      coverageCandidate: true,
    },
    {
      id: 'optional-chaining',
      concern: 'testability',
      category: 'branch-noise',
      key: '?.',
      severity: 'warning',
      penalty: 6,
      pattern: /\?\.(?!\s*\()/,
      description: 'Optional chaining can create hidden branch accounting in generated coverage data.',
      suggestion: 'Test the nullish path when it is meaningful; otherwise isolate defensive access at a boundary.',
      coverageCandidate: true,
    },
    {
      id: 'ternary',
      concern: 'testability',
      category: 'branch-noise',
      key: '?:',
      severity: 'warning',
      penalty: 10,
      pattern: /(?:=|\(|\[|{|return\s+|=>\s*)[^?\n:]+?\?\s*[^:\n]+?\s*:\s*[^;\n,)]+/,
      description: 'A ternary creates two outcomes and can make uncovered behavior less obvious.',
      suggestion: 'Test both outcomes when meaningful or extract the decision from JSX/inline expressions.',
      coverageCandidate: true,
    },
    {
      id: 'default-destructured-prop',
      concern: 'testability',
      category: 'branch-noise',
      key: 'prop=',
      severity: 'warning',
      penalty: 7,
      pattern: /[{,]\s*\w+\s*=\s*[^,}]+/,
      description: 'Default destructured values can produce coverage branches that are easy to overlook.',
      suggestion: 'Test omitted and provided values when meaningful, or resolve the default in an explicit helper.',
      coverageCandidate: true,
    },
    {
      id: 'coverage-ignore-comment',
      concern: 'testability',
      category: 'policy',
      key: 'coverage-ignore',
      severity: 'error',
      penalty: 20,
      pattern: /(v8|istanbul|c8)\s+ignore/i,
      description: 'Direct coverage-ignore comments bypass the scanner accountability model.',
      suggestion: 'Use a scanner-approved coverage exclusion rule with a documented reason instead.',
    },
    {
      id: 'eslint-disable-comment',
      concern: 'testability',
      category: 'policy',
      key: 'eslint-disable',
      severity: 'warning',
      penalty: 20,
      pattern: /eslint-disable/,
      description: 'ESLint disable comments can hide maintainability or correctness issues.',
      suggestion: 'Fix the underlying issue or document an intentional project policy exception.',
    },
  ];
  